= Pack (alpha)

Package up Clojure projects in various ways, based on a deps.edn file.

== Usage

=== Lambda

The lambda approach will generate a zip which can be uploaded to AWS.

[source,clojure]
----
clj -Sdeps '{:deps {pack/pack.alpha {:git/url "https://github.com/juxt/pack.alpha.git" :sha "eed89476315661e2389d5d078ec17375bec3efa5"}}}' -m mach.pack.alpha.aws-lambda deps.edn lambda.zip build_dir
----

In this example:

* `deps.edn` is the location of the deps.edn to consume.
* lambda.zip is where to write the package to.
* build_dir is a directory containing extra paths to add, for example it may be where you compile classes to, or write built css to.

=== Uberjar

==== Capsule

[source,clojure]
----
$ clj -Sdeps '{:deps {pack/pack.alpha {:git/url "https://github.com/juxt/pack.alpha.git" :sha "bb2c5a2c78aca9328e023b029c06ba0efdd1e3b7"}}}' -m mach.pack.alpha.capsule deps.edn uberjar.jar build_dir my.cool.application 0.1.0-6-g46100ae
$ java -jar uberjar.jar -m myapp.main
----

In this example:

* `deps.edn` is the location of the deps.edn to consume
* uberjar.jar is the resulting jar name
* build_dir is a directory containing extra paths to add, for example it may be where you compile classes to, or write built css to.
* `my.cool.application` is your Application-ID, this must be unique to your jar
* `0.1.0-6-g46100ae` is your Application-Version, I've been using `$(git describe)` to populate this

The jar's entrypoint is set to clojure.main, and therefore the jar takes all of the same options as clojure.main.

INFO: In the future I will extend Capsule support to include capsule-specific features, such as caplets and many of the related manifest attributes.

==== jdsoft JarClassLoader

WARNING: jcl is based on link:http://www.jdotsoft.com/JarClassLoader.php[Jar Class Loader] which is licensed under GPLv3.

[source,clojure]
----
$ clj -Sdeps '{:deps {pack/pack.alpha {:git/url "https://github.com/juxt/pack.alpha.git" :sha "eed89476315661e2389d5d078ec17375bec3efa5"}}}' -m mach.pack.alpha.jcl deps.edn uberjar.jar build_dir
$ java -jar uberjar.jar -m myapp.main
----

In this example:

* `deps.edn` is the location of the deps.edn to consume.
* uberjar.jar is the resulting jar name
* build_dir is a directory containing extra paths to add, for example it may be where you compile classes to, or write built css to.

The jar's entrypoint is set to clojure.main, and therefore the jar takes all of the same options as clojure.main.

== Building

Run clj to update the pom.xml

----
$ clj -Spom
----

Remove the `<sourceDirectory>` tag from the pom.xml.

Then use maven as normal:

----
$ mvn install
$ mvn deploy
----

to install locally.
