= Pack (alpha)

Package up Clojure projects in various ways, based on a deps.edn file.

== Usage

=== Auto-add to project

Pack can add itself to your deps.edn automatically.
It will not modify your indentation style at all.
This is alpha, but so is everything else in this project.

It can be run at later times, in order to automatically bump the sha in your deps.edn.
It will continue to work even if you rename the default `:pack` alias to something else.

NOTE: This isn't infallible.  Please let me know if I break your indentation.

[source,clojure]
----
clj -Sdeps '{:deps {pack/pack.alpha {:git/url "https://github.com/juxt/pack.alpha.git" :sha "dccf2134bcf03726a9465d2b9997c42e5cd91bff"}}}' -m mach.pack.alpha.inject 1d455f6c591f440560c57a29e6d930004d735dcf
----

The following examples assume you have run this.

=== Lambda

The lambda approach will generate a zip which can be uploaded to AWS.

[source,clojure]
----
clj -A:pack mach.pack.alpha.aws-lambda deps.edn lambda.zip build_dir
----

In this example:

* `deps.edn` is the location of the deps.edn to consume.
* lambda.zip is where to write the package to.
* build_dir is a directory containing extra paths to add, for example it may be where you compile classes to, or write built css to.

=== Uberjar

"Uberjar-ing" consists of packaging you application into one all-encompassing JAR (Java ARchive) file, called an "Uberjar", which can then be executed using `java -jar myapp.jar ARG1 ARG2 ARG3...`.

Pack provides several approaches for creating an Uberjar:

==== Capsule

This consists of building an Uberjar using http://www.capsule.io/[Parallel Universe's Capsule].

[source,clojure]
----
$ clj -A:pack mach.pack.alpha.capsule uberjar.jar -e build-dir --application-id mycoolapp --application-version "$(git describe)" -m myapp.main
$ java -jar uberjar.jar
----

[source]
----
Usage: clj -m mach.pack.alpha.capsule [options] <path/to/output.jar>
  -m, --main SYMBOL                           main namespace
      --application-id STRING                 globally unique name for application, used for caching
      --application-version STRING            unique version for this uberjar, used for caching
      --system-properties STRING              space-separated list of propName=value pairs, specifying JVM System Properties which will be passed to the application. Maps to the 'System-Properties' entry in the Capsule Manifest.
      --jvm-args STRING                       space-separated list of JVM argument that will be used to launch the application (e.g "-server -Xms200m -Xmx600m"). Maps to the 'JVM-Args' entry in the Capsule Manifest.
  -e, --extra-path STRING                     add directory to classpath for building
  -d, --deps STRING                 deps.edn  deps.edn file location
  -M, --manifest-entry STRING                 a "Key: Value" pair that will be appended to the Capsule Manifest; useful for conveying arbitrary Manifest entries to the Capsule Manifest. Can be repeated to supply several entries.
  -h, --help                                  show this help
----

The main *does not* need `:gen-class`, it follows the same semantics as clojure.main's `-m main`.
If main is not specified, it will default to `clojure.main`, meaning it can take options like `-m` or `-r`.
`extra-path` is useful for adding clojurescript & css to the resulting jar.
It can be used multiple times.

[CAUTION]
.Executing a Capsule JAR with JVM args / System Properties
====
As mentioned in the http://www.capsule.io/user-guide/#the-capsule-execution-process[Capsule docs], when you execute a Capsule-packaged Uberjar, 2 Java processes are actually run: the Capsule launcher, and your application process.

In particular, JVM args and System Properties passed to the `java` command will apply to both processes, which if you're not careful can result in waste of resources and collisions; for example:

* If you pass the `-Xms2g` JVM arg, you've just allocated 2 Gigabytes of unnecessary RAM for the Capsule launcher
* If you pass the `-Dcom.sun.management.jmxremote.port=7091` System Property you will get an error, as both Java processes try to use the `7091` port for JMX.

The way to prevent this is to pass special options that will only apply to the application process.
See the http://www.capsule.io/user-guide/#jvm-arguments-system-properties-environment-variables-and-agents[related Capsule documentation].
====

INFO: In the future I will extend Capsule support to include capsule-specific features, such as caplets and many of the related manifest attributes.

==== OneJAR

link:http://one-jar.sourceforge.net/[OneJAR] builder.
This is a suitable replacement for jdsoft JCL, without the GPL license.
It's especially practical where you can't extract into a `~/.capsule` directory, or don't need to bake in JVM args.

[source]
----
Usage: clj -m mach.pack.alpha.one-jar [options] <path/to/output.jar>

Options:
  -e, --extra-path STRING            add directory to classpath for building
  -d, --deps STRING        deps.edn  deps.edn file location
  -h, --help                         show this help

output.jar is where to put the output uberjar. Leading directories will be created.
----

Example:

[source,bash]
----
$ clj -A:pack mach.pack.alpha.one-jar output.jar
$ java -jar output.jar
----

==== jdsoft JarClassLoader

WARNING: This has been removed due to my own licensing concerns about co-locating the source with my own.
